// Code generated by github.com/mchenriques22/pergolator, DO NOT EDIT.
package maptests

import (
	"reflect"
	"strconv"
	"strings"

	"github.com/mchenriques22/pergolator/tree"
)

type StructPercolator struct {
	fn func(document *Struct) bool
}

// Percolate percolates the document with the percolator's query.
// It will return a boolean indicating if the query matches the document.
func (p *StructPercolator) Percolate(document *Struct) bool {
	return p.fn(document)
}

// NewStructPercolatorConstructor is a constructor of percolators.
// Every percolator it creates will use the parser provided to the constructor.
func NewStructPercolatorConstructor(parseFn tree.ParseFn, modifiers ...tree.Modifiers) func(query string) (*StructPercolator, error) {
	return func(query string) (*StructPercolator, error) {
		return NewStructPercolator(parseFn, query, modifiers...)
	}
}

// NewStructPercolator creates a percolator with a given query and a given parser.
// It returns an error if the parsing failed.
func NewStructPercolator(parseFn tree.ParseFn, query string, modifiers ...tree.Modifiers) (*StructPercolator, error) {
	root, err := parseFn(query)
	if err != nil {
		return nil, err
	}

	for _, modifier := range modifiers {
		root = modifier(root)
		if _, isEmpty := root.(*tree.Empty); isEmpty {
			// If the query is empty, we return a percolator that always returns false
			return &StructPercolator{fn: pStructFalseFn}, nil
		}
	}

	return &StructPercolator{fn: updateNodeStruct(root)}, nil
}

func updateNodeStruct(root tree.Expr) func(document *Struct) bool {
	switch r := root.(type) {
	case *tree.And:
		fns := make([]func(document *Struct) bool, 0, len(r.Children))
		for _, child := range r.Children {
			fn := updateNodeStruct(child)

			// Optimize the case where one of the children is always false
			if reflect.ValueOf(fn).Pointer() == reflect.ValueOf(pStructFalseFn).Pointer() {
				return pStructFalseFn
			}
			fns = append(fns, fn)
		}

		return func(document *Struct) bool {
			for _, fn := range fns {
				if !fn(document) {
					return false
				}
			}
			return true
		}
	case *tree.Or:
		fns := make([]func(document *Struct) bool, 0, len(r.Children))
		for _, child := range r.Children {
			fn := updateNodeStruct(child)

			// Optimize the case where one of the children is always false
			if reflect.ValueOf(fn).Pointer() == reflect.ValueOf(pStructFalseFn).Pointer() {
				continue
			}
			fns = append(fns, fn)
		}

		if len(fns) == 0 {
			return pStructFalseFn
		}

		return func(document *Struct) bool {
			for _, fn := range fns {
				if fn(document) {
					return true
				}
			}
			return false
		}
	case *tree.Not:
		child := updateNodeStruct(r.Child)
		return func(document *Struct) bool {
			return !child(document)
		}
	case *tree.Query:
		return pStructQuery(r)
	}

	return pStructFalseFn
}

type NestedPercolator struct {
	fn func(document *Nested) bool
}

// Percolate percolates the document with the percolator's query.
// It will return a boolean indicating if the query matches the document.
func (p *NestedPercolator) Percolate(document *Nested) bool {
	return p.fn(document)
}

// NewNestedPercolatorConstructor is a constructor of percolators.
// Every percolator it creates will use the parser provided to the constructor.
func NewNestedPercolatorConstructor(parseFn tree.ParseFn, modifiers ...tree.Modifiers) func(query string) (*NestedPercolator, error) {
	return func(query string) (*NestedPercolator, error) {
		return NewNestedPercolator(parseFn, query, modifiers...)
	}
}

// NewNestedPercolator creates a percolator with a given query and a given parser.
// It returns an error if the parsing failed.
func NewNestedPercolator(parseFn tree.ParseFn, query string, modifiers ...tree.Modifiers) (*NestedPercolator, error) {
	root, err := parseFn(query)
	if err != nil {
		return nil, err
	}

	for _, modifier := range modifiers {
		root = modifier(root)
		if _, isEmpty := root.(*tree.Empty); isEmpty {
			// If the query is empty, we return a percolator that always returns false
			return &NestedPercolator{fn: pNestedFalseFn}, nil
		}
	}

	return &NestedPercolator{fn: updateNodeNested(root)}, nil
}

func updateNodeNested(root tree.Expr) func(document *Nested) bool {
	switch r := root.(type) {
	case *tree.And:
		fns := make([]func(document *Nested) bool, 0, len(r.Children))
		for _, child := range r.Children {
			fn := updateNodeNested(child)

			// Optimize the case where one of the children is always false
			if reflect.ValueOf(fn).Pointer() == reflect.ValueOf(pNestedFalseFn).Pointer() {
				return pNestedFalseFn
			}
			fns = append(fns, fn)
		}

		return func(document *Nested) bool {
			for _, fn := range fns {
				if !fn(document) {
					return false
				}
			}
			return true
		}
	case *tree.Or:
		fns := make([]func(document *Nested) bool, 0, len(r.Children))
		for _, child := range r.Children {
			fn := updateNodeNested(child)

			// Optimize the case where one of the children is always false
			if reflect.ValueOf(fn).Pointer() == reflect.ValueOf(pNestedFalseFn).Pointer() {
				continue
			}
			fns = append(fns, fn)
		}

		if len(fns) == 0 {
			return pNestedFalseFn
		}

		return func(document *Nested) bool {
			for _, fn := range fns {
				if fn(document) {
					return true
				}
			}
			return false
		}
	case *tree.Not:
		child := updateNodeNested(r.Child)
		return func(document *Nested) bool {
			return !child(document)
		}
	case *tree.Query:
		return pNestedQuery(r)
	}

	return pNestedFalseFn
}

func pStructQuery(query *tree.Query) func(*Struct) bool {
	key, suffix, _ := strings.Cut(query.Key, ".")
	_ = suffix
	switch key {
	case "map_string_string":
		parsed := query.Value
		return func(document *Struct) bool {
			value, found := document.MapStringString[suffix]
			return found && value == parsed
		}
	case "map_string_float32":
		tmp, err := strconv.ParseFloat(query.Value, 32)
		if err != nil {
			return pStructFalseFn
		}
		parsed := float32(tmp)
		return func(document *Struct) bool {
			value, found := document.MapStringFloat32[suffix]
			return found && value == parsed
		}
	case "map_string_nested":
		return pStructFalseFn
	default:
		return pStructFalseFn
	}
}

func pStructFalseFn(_ *Struct) bool {
	return false
}

func pNestedQuery(query *tree.Query) func(*Nested) bool {
	key, suffix, _ := strings.Cut(query.Key, ".")
	_ = suffix
	switch key {
	case "value":
		parsed := query.Value
		return func(document *Nested) bool {
			return document.Value == parsed
		}
	default:
		return pNestedFalseFn
	}
}

func pNestedFalseFn(_ *Nested) bool {
	return false
}
