// Code generated by github.com/mchenriques22/pergolator, DO NOT EDIT.
package tags

import (
	"reflect"
	"strings"

	"github.com/mchenriques22/pergolator/tree"
)

type MyStructPercolator struct {
	fn func(document *MyStruct) bool
}

// Percolate percolates the document with the percolator's query.
// It will return a boolean indicating if the query matches the document.
func (p *MyStructPercolator) Percolate(document *MyStruct) bool {
	return p.fn(document)
}

// NewMyStructPercolatorConstructor is a constructor of percolators.
// Every percolator it creates will use the parser provided to the constructor.
func NewMyStructPercolatorConstructor(parseFn tree.ParseFn, modifiers ...tree.Modifiers) func(query string) (*MyStructPercolator, error) {
	return func(query string) (*MyStructPercolator, error) {
		return NewMyStructPercolator(parseFn, query, modifiers...)
	}
}

// NewMyStructPercolator creates a percolator with a given query and a given parser.
// It returns an error if the parsing failed.
func NewMyStructPercolator(parseFn tree.ParseFn, query string, modifiers ...tree.Modifiers) (*MyStructPercolator, error) {
	root, err := parseFn(query)
	if err != nil {
		return nil, err
	}

	for _, modifier := range modifiers {
		root = modifier(root)
		if _, isEmpty := root.(*tree.Empty); isEmpty {
			// If the query is empty, we return a percolator that always returns false
			return &MyStructPercolator{fn: pMyStructFalseFn}, nil
		}
	}

	return &MyStructPercolator{fn: updateNodeMyStruct(root)}, nil
}

func updateNodeMyStruct(root tree.Expr) func(document *MyStruct) bool {
	switch r := root.(type) {
	case *tree.And:
		fns := make([]func(document *MyStruct) bool, 0, len(r.Children))
		for _, child := range r.Children {
			fn := updateNodeMyStruct(child)

			// Optimize the case where one of the children is always false
			if reflect.ValueOf(fn).Pointer() == reflect.ValueOf(pMyStructFalseFn).Pointer() {
				return pMyStructFalseFn
			}
			fns = append(fns, fn)
		}

		return func(document *MyStruct) bool {
			for _, fn := range fns {
				if !fn(document) {
					return false
				}
			}
			return true
		}
	case *tree.Or:
		fns := make([]func(document *MyStruct) bool, 0, len(r.Children))
		for _, child := range r.Children {
			fn := updateNodeMyStruct(child)

			// Optimize the case where one of the children is always false
			if reflect.ValueOf(fn).Pointer() == reflect.ValueOf(pMyStructFalseFn).Pointer() {
				continue
			}
			fns = append(fns, fn)
		}

		if len(fns) == 0 {
			return pMyStructFalseFn
		}

		return func(document *MyStruct) bool {
			for _, fn := range fns {
				if fn(document) {
					return true
				}
			}
			return false
		}
	case *tree.Not:
		child := updateNodeMyStruct(r.Child)
		return func(document *MyStruct) bool {
			return !child(document)
		}
	case *tree.Query:
		return pMyStructQuery(r)
	}

	return pMyStructFalseFn
}

type MyStructBPercolator struct {
	fn func(document *MyStructB) bool
}

// Percolate percolates the document with the percolator's query.
// It will return a boolean indicating if the query matches the document.
func (p *MyStructBPercolator) Percolate(document *MyStructB) bool {
	return p.fn(document)
}

// NewMyStructBPercolatorConstructor is a constructor of percolators.
// Every percolator it creates will use the parser provided to the constructor.
func NewMyStructBPercolatorConstructor(parseFn tree.ParseFn, modifiers ...tree.Modifiers) func(query string) (*MyStructBPercolator, error) {
	return func(query string) (*MyStructBPercolator, error) {
		return NewMyStructBPercolator(parseFn, query, modifiers...)
	}
}

// NewMyStructBPercolator creates a percolator with a given query and a given parser.
// It returns an error if the parsing failed.
func NewMyStructBPercolator(parseFn tree.ParseFn, query string, modifiers ...tree.Modifiers) (*MyStructBPercolator, error) {
	root, err := parseFn(query)
	if err != nil {
		return nil, err
	}

	for _, modifier := range modifiers {
		root = modifier(root)
		if _, isEmpty := root.(*tree.Empty); isEmpty {
			// If the query is empty, we return a percolator that always returns false
			return &MyStructBPercolator{fn: pMyStructBFalseFn}, nil
		}
	}

	return &MyStructBPercolator{fn: updateNodeMyStructB(root)}, nil
}

func updateNodeMyStructB(root tree.Expr) func(document *MyStructB) bool {
	switch r := root.(type) {
	case *tree.And:
		fns := make([]func(document *MyStructB) bool, 0, len(r.Children))
		for _, child := range r.Children {
			fn := updateNodeMyStructB(child)

			// Optimize the case where one of the children is always false
			if reflect.ValueOf(fn).Pointer() == reflect.ValueOf(pMyStructBFalseFn).Pointer() {
				return pMyStructBFalseFn
			}
			fns = append(fns, fn)
		}

		return func(document *MyStructB) bool {
			for _, fn := range fns {
				if !fn(document) {
					return false
				}
			}
			return true
		}
	case *tree.Or:
		fns := make([]func(document *MyStructB) bool, 0, len(r.Children))
		for _, child := range r.Children {
			fn := updateNodeMyStructB(child)

			// Optimize the case where one of the children is always false
			if reflect.ValueOf(fn).Pointer() == reflect.ValueOf(pMyStructBFalseFn).Pointer() {
				continue
			}
			fns = append(fns, fn)
		}

		if len(fns) == 0 {
			return pMyStructBFalseFn
		}

		return func(document *MyStructB) bool {
			for _, fn := range fns {
				if fn(document) {
					return true
				}
			}
			return false
		}
	case *tree.Not:
		child := updateNodeMyStructB(r.Child)
		return func(document *MyStructB) bool {
			return !child(document)
		}
	case *tree.Query:
		return pMyStructBQuery(r)
	}

	return pMyStructBFalseFn
}

func pMyStructQuery(query *tree.Query) func(*MyStruct) bool {
	key, suffix, _ := strings.Cut(query.Key, ".")
	_ = suffix
	switch key {

	default:
		fnFieldA := pMyStructBQuery(query)
		fnFieldAEnabled := reflect.ValueOf(fnFieldA).Pointer() != reflect.ValueOf(pMyStructBFalseFn).Pointer()
		return func(document *MyStruct) bool {
			return fnFieldAEnabled && fnFieldA(&document.FieldA)
		}
	}
}

func pMyStructFalseFn(_ *MyStruct) bool {
	return false
}

func pMyStructBQuery(query *tree.Query) func(*MyStructB) bool {
	key, suffix, _ := strings.Cut(query.Key, ".")
	_ = suffix
	switch key {
	case "FieldB":
		parsed := query.Value
		return func(document *MyStructB) bool {
			return document.FieldB == parsed
		}
	default:
		return pMyStructBFalseFn
	}
}

func pMyStructBFalseFn(_ *MyStructB) bool {
	return false
}
