// Code generated by github.com/antoninferrand/pergolator, DO NOT EDIT.
package basic

import (
	"reflect"
	"strconv"
	"strings"

	"github.com/antoninferrand/pergolator/tree"
)

type StructPercolator struct {
	fn func(document *Struct) bool
}

// Percolate percolates the document with the percolator's query.
// It will return a boolean indicating if the query matches the document.
func (p *StructPercolator) Percolate(document *Struct) bool {
	return p.fn(document)
}

// NewStructPercolatorConstructor is a constructor of percolators.
// Every percolator it creates will use the parser provided to the constructor.
func NewStructPercolatorConstructor(parseFn tree.ParseFn, modifiers ...tree.Modifiers) func(query string) (*StructPercolator, error) {
	return func(query string) (*StructPercolator, error) {
		return NewStructPercolator(parseFn, query, modifiers...)
	}
}

// NewStructPercolator creates a percolator with a given query and a given parser.
// It returns an error if the parsing failed.
func NewStructPercolator(parseFn tree.ParseFn, query string, modifiers ...tree.Modifiers) (*StructPercolator, error) {
	root, err := parseFn(query)
	if err != nil {
		return nil, err
	}

	for _, modifier := range modifiers {
		root = modifier(root)
		if _, isEmpty := root.(*tree.Empty); isEmpty {
			// If the query is empty, we return a percolator that always returns false
			return &StructPercolator{fn: pStructFalseFn}, nil
		}
	}

	return &StructPercolator{fn: updateNodeStruct(root)}, nil
}

func updateNodeStruct(root tree.Expr) func(document *Struct) bool {
	switch r := root.(type) {
	case *tree.And:
		fns := make([]func(document *Struct) bool, 0, len(r.Children))
		for _, child := range r.Children {
			fn := updateNodeStruct(child)

			// Optimize the case where one of the children is always false
			if reflect.ValueOf(fn).Pointer() == reflect.ValueOf(pStructFalseFn).Pointer() {
				return pStructFalseFn
			}
			fns = append(fns, fn)
		}

		return func(document *Struct) bool {
			for _, fn := range fns {
				if !fn(document) {
					return false
				}
			}
			return true
		}
	case *tree.Or:
		fns := make([]func(document *Struct) bool, 0, len(r.Children))
		for _, child := range r.Children {
			fn := updateNodeStruct(child)

			// Optimize the case where one of the children is always false
			if reflect.ValueOf(fn).Pointer() == reflect.ValueOf(pStructFalseFn).Pointer() {
				continue
			}
			fns = append(fns, fn)
		}

		if len(fns) == 0 {
			return pStructFalseFn
		}

		return func(document *Struct) bool {
			for _, fn := range fns {
				if fn(document) {
					return true
				}
			}
			return false
		}
	case *tree.Not:
		child := updateNodeStruct(r.Child)
		return func(document *Struct) bool {
			return !child(document)
		}
	case *tree.Query:
		return pStructQuery(r)
	}

	return pStructFalseFn
}

func pStructQuery(query *tree.Query) func(*Struct) bool {
	key, suffix, _ := strings.Cut(query.Key, ".")
	_ = suffix
	switch key {
	case "BasicString":
		parsed := query.Value
		return func(document *Struct) bool {
			return document.BasicString == parsed
		}
	case "BasicInt":
		tmp, err := strconv.ParseInt(query.Value, 10, 64)
		if err != nil {
			return pStructFalseFn
		}
		parsed := int(tmp)
		switch query.Sign {
		case tree.Eq:
			return func(document *Struct) bool {
				return document.BasicInt == parsed
			}
		case tree.Gte:
			return func(document *Struct) bool {
				return document.BasicInt >= parsed
			}
		case tree.Gt:
			return func(document *Struct) bool {
				return document.BasicInt > parsed
			}
		case tree.Lte:
			return func(document *Struct) bool {
				return document.BasicInt <= parsed
			}
		case tree.Lt:
			return func(document *Struct) bool {
				return document.BasicInt < parsed
			}
		default:
			return pStructFalseFn
		}
	case "BasicInt8":
		tmp, err := strconv.ParseInt(query.Value, 10, 8)
		if err != nil {
			return pStructFalseFn
		}
		parsed := int8(tmp)
		switch query.Sign {
		case tree.Eq:
			return func(document *Struct) bool {
				return document.BasicInt8 == parsed
			}
		case tree.Gte:
			return func(document *Struct) bool {
				return document.BasicInt8 >= parsed
			}
		case tree.Gt:
			return func(document *Struct) bool {
				return document.BasicInt8 > parsed
			}
		case tree.Lte:
			return func(document *Struct) bool {
				return document.BasicInt8 <= parsed
			}
		case tree.Lt:
			return func(document *Struct) bool {
				return document.BasicInt8 < parsed
			}
		default:
			return pStructFalseFn
		}
	case "BasicInt16":
		tmp, err := strconv.ParseInt(query.Value, 10, 16)
		if err != nil {
			return pStructFalseFn
		}
		parsed := int16(tmp)
		switch query.Sign {
		case tree.Eq:
			return func(document *Struct) bool {
				return document.BasicInt16 == parsed
			}
		case tree.Gte:
			return func(document *Struct) bool {
				return document.BasicInt16 >= parsed
			}
		case tree.Gt:
			return func(document *Struct) bool {
				return document.BasicInt16 > parsed
			}
		case tree.Lte:
			return func(document *Struct) bool {
				return document.BasicInt16 <= parsed
			}
		case tree.Lt:
			return func(document *Struct) bool {
				return document.BasicInt16 < parsed
			}
		default:
			return pStructFalseFn
		}
	case "BasicInt32":
		tmp, err := strconv.ParseInt(query.Value, 10, 32)
		if err != nil {
			return pStructFalseFn
		}
		parsed := int32(tmp)
		switch query.Sign {
		case tree.Eq:
			return func(document *Struct) bool {
				return document.BasicInt32 == parsed
			}
		case tree.Gte:
			return func(document *Struct) bool {
				return document.BasicInt32 >= parsed
			}
		case tree.Gt:
			return func(document *Struct) bool {
				return document.BasicInt32 > parsed
			}
		case tree.Lte:
			return func(document *Struct) bool {
				return document.BasicInt32 <= parsed
			}
		case tree.Lt:
			return func(document *Struct) bool {
				return document.BasicInt32 < parsed
			}
		default:
			return pStructFalseFn
		}
	case "BasicInt64":
		parsed, err := strconv.ParseInt(query.Value, 10, 64)
		if err != nil {
			return pStructFalseFn
		}
		switch query.Sign {
		case tree.Eq:
			return func(document *Struct) bool {
				return document.BasicInt64 == parsed
			}
		case tree.Gte:
			return func(document *Struct) bool {
				return document.BasicInt64 >= parsed
			}
		case tree.Gt:
			return func(document *Struct) bool {
				return document.BasicInt64 > parsed
			}
		case tree.Lte:
			return func(document *Struct) bool {
				return document.BasicInt64 <= parsed
			}
		case tree.Lt:
			return func(document *Struct) bool {
				return document.BasicInt64 < parsed
			}
		default:
			return pStructFalseFn
		}
	case "BasicUint":
		tmp, err := strconv.ParseUint(query.Value, 10, 64)
		if err != nil {
			return pStructFalseFn
		}
		parsed := uint(tmp)
		switch query.Sign {
		case tree.Eq:
			return func(document *Struct) bool {
				return document.BasicUint == parsed
			}
		case tree.Gte:
			return func(document *Struct) bool {
				return document.BasicUint >= parsed
			}
		case tree.Gt:
			return func(document *Struct) bool {
				return document.BasicUint > parsed
			}
		case tree.Lte:
			return func(document *Struct) bool {
				return document.BasicUint <= parsed
			}
		case tree.Lt:
			return func(document *Struct) bool {
				return document.BasicUint < parsed
			}
		default:
			return pStructFalseFn
		}
	case "BasicUint8":
		tmp, err := strconv.ParseUint(query.Value, 10, 8)
		if err != nil {
			return pStructFalseFn
		}
		parsed := uint8(tmp)
		switch query.Sign {
		case tree.Eq:
			return func(document *Struct) bool {
				return document.BasicUint8 == parsed
			}
		case tree.Gte:
			return func(document *Struct) bool {
				return document.BasicUint8 >= parsed
			}
		case tree.Gt:
			return func(document *Struct) bool {
				return document.BasicUint8 > parsed
			}
		case tree.Lte:
			return func(document *Struct) bool {
				return document.BasicUint8 <= parsed
			}
		case tree.Lt:
			return func(document *Struct) bool {
				return document.BasicUint8 < parsed
			}
		default:
			return pStructFalseFn
		}
	case "BasicUint16":
		tmp, err := strconv.ParseUint(query.Value, 10, 16)
		if err != nil {
			return pStructFalseFn
		}
		parsed := uint16(tmp)
		switch query.Sign {
		case tree.Eq:
			return func(document *Struct) bool {
				return document.BasicUint16 == parsed
			}
		case tree.Gte:
			return func(document *Struct) bool {
				return document.BasicUint16 >= parsed
			}
		case tree.Gt:
			return func(document *Struct) bool {
				return document.BasicUint16 > parsed
			}
		case tree.Lte:
			return func(document *Struct) bool {
				return document.BasicUint16 <= parsed
			}
		case tree.Lt:
			return func(document *Struct) bool {
				return document.BasicUint16 < parsed
			}
		default:
			return pStructFalseFn
		}
	case "BasicUint32":
		tmp, err := strconv.ParseUint(query.Value, 10, 32)
		if err != nil {
			return pStructFalseFn
		}
		parsed := uint32(tmp)
		switch query.Sign {
		case tree.Eq:
			return func(document *Struct) bool {
				return document.BasicUint32 == parsed
			}
		case tree.Gte:
			return func(document *Struct) bool {
				return document.BasicUint32 >= parsed
			}
		case tree.Gt:
			return func(document *Struct) bool {
				return document.BasicUint32 > parsed
			}
		case tree.Lte:
			return func(document *Struct) bool {
				return document.BasicUint32 <= parsed
			}
		case tree.Lt:
			return func(document *Struct) bool {
				return document.BasicUint32 < parsed
			}
		default:
			return pStructFalseFn
		}
	case "BasicUint64":
		parsed, err := strconv.ParseUint(query.Value, 10, 64)
		if err != nil {
			return pStructFalseFn
		}
		switch query.Sign {
		case tree.Eq:
			return func(document *Struct) bool {
				return document.BasicUint64 == parsed
			}
		case tree.Gte:
			return func(document *Struct) bool {
				return document.BasicUint64 >= parsed
			}
		case tree.Gt:
			return func(document *Struct) bool {
				return document.BasicUint64 > parsed
			}
		case tree.Lte:
			return func(document *Struct) bool {
				return document.BasicUint64 <= parsed
			}
		case tree.Lt:
			return func(document *Struct) bool {
				return document.BasicUint64 < parsed
			}
		default:
			return pStructFalseFn
		}
	case "BasicFloat32":
		tmp, err := strconv.ParseFloat(query.Value, 32)
		if err != nil {
			return pStructFalseFn
		}
		parsed := float32(tmp)
		switch query.Sign {
		case tree.Eq:
			return func(document *Struct) bool {
				return document.BasicFloat32 == parsed
			}
		case tree.Gte:
			return func(document *Struct) bool {
				return document.BasicFloat32 >= parsed
			}
		case tree.Gt:
			return func(document *Struct) bool {
				return document.BasicFloat32 > parsed
			}
		case tree.Lte:
			return func(document *Struct) bool {
				return document.BasicFloat32 <= parsed
			}
		case tree.Lt:
			return func(document *Struct) bool {
				return document.BasicFloat32 < parsed
			}
		default:
			return pStructFalseFn
		}
	case "BasicFloat64":
		parsed, err := strconv.ParseFloat(query.Value, 64)
		if err != nil {
			return pStructFalseFn
		}
		switch query.Sign {
		case tree.Eq:
			return func(document *Struct) bool {
				return document.BasicFloat64 == parsed
			}
		case tree.Gte:
			return func(document *Struct) bool {
				return document.BasicFloat64 >= parsed
			}
		case tree.Gt:
			return func(document *Struct) bool {
				return document.BasicFloat64 > parsed
			}
		case tree.Lte:
			return func(document *Struct) bool {
				return document.BasicFloat64 <= parsed
			}
		case tree.Lt:
			return func(document *Struct) bool {
				return document.BasicFloat64 < parsed
			}
		default:
			return pStructFalseFn
		}
	case "BasicBool":
		parsed, err := strconv.ParseBool(query.Value)
		if err != nil {
			return pStructFalseFn
		}
		return func(document *Struct) bool {
			return document.BasicBool == parsed
		}
	default:
		return pStructFalseFn
	}
}

func pStructFalseFn(_ *Struct) bool {
	return false
}
